---
- name: Install UFW
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: Configure firewall - Allow SSH
  ufw:
    rule: allow
    port: ssh
    proto: tcp

- name: Configure firewall - Allow Registry HTTP
  ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Configure firewall - Allow Registry HTTPS
  ufw:
    rule: allow
    port: '443'
    proto: tcp

- name: Configure firewall - Enable UFW
  ufw:
    state: enabled
    policy: deny